[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
credit_score = "B3AdtMZWq4K4XHuRjDwv88BqYxg4YYCF6FtKnvuZzoNB"
crop_batch = "7M66PRBrpGP2mT1tTUmaENEGaQ3M9VFCtjEAMyemxKMh"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
