[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crop-batch = "A5aLLkRbgS6oqSo3ikmc7Dww3dF6BHdp6znDG4uXtv1b"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
